spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/llbooks?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: lldj
    password: lldj123414
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update