spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/final__2022_10_08__test??useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: lldj
    password: lldj123414
  jpa:
    hibernate:
      ddl-auto: create